# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Cyrus Sethna"
description: > # this means to ignore newlines until "email:"
   Civic Technologist

email: csethna@gmail.com
#blog logo
logo: "/assets/images/cs_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Cyrus Sethna'
author: 'Cyrus Sethna'
author_image: "/assets/images/headshot.jpg"

paginate:	5

url: "http://csethna.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@c_sethna'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/c_sethna
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

 - icon:	briefcase
   url:	https://usds.gov
   desc: U.S. Digital Service
   share_url: https://www.facebook.com/sharer.php
   share_title: ?t=
   share_link: "&amp;u="

  - icon:	linkedin
    url:	https://linkedin.com/in/csethna
    desc:	Connect on LinkedIn
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
